# Generated by Django 4.2.3 on 2023-08-09 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 0, 30, 25, 977996, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicacion'),
        ),
    ]
